export interface Destination {
  name: string;
  country: string;
  price: number;
  rating: number;
  slug: string;
  image: string;
  tags: string[];
}

export interface Deal {
  id: number;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  price: number;
  originalPrice: number;
  image: string;
  badge: string;
  badgeEn: string;
  tags: string[];
}

export const destinations: Destination[] = [
  { name: "Paris", country: "França", price: 2490, rating: 4.8, slug: "paris", image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=450&fit=crop", tags: ["paris", "franca", "europa"] },
  { name: "Rio de Janeiro", country: "Brasil", price: 1290, rating: 4.7, slug: "rio", image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&h=450&fit=crop", tags: ["rio", "brasil", "america do sul"] },
  { name: "Tokyo", country: "Japão", price: 4990, rating: 4.9, slug: "tokyo", image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=450&fit=crop", tags: ["tokyo", "japao", "asia"] },
  { name: "Roma", country: "Itália", price: 2290, rating: 4.6, slug: "rome", image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&h=450&fit=crop", tags: ["roma", "italia", "europa"] },
  { name: "Bali", country: "Indonésia", price: 3290, rating: 4.8, slug: "bali", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=450&fit=crop", tags: ["bali", "indonesia", "asia"] },
  { name: "New York", country: "Estados Unidos", price: 2990, rating: 4.5, slug: "new-york", image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&h=450&fit=crop", tags: ["new york", "eua", "estados unidos", "america do norte"] },
  { name: "Londres", country: "Inglaterra", price: 2790, rating: 4.7, slug: "london", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&h=450&fit=crop", tags: ["londres", "inglaterra", "europa", "uk"] },
  { name: "Barcelona", country: "Espanha", price: 2190, rating: 4.6, slug: "barcelona", image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&h=450&fit=crop", tags: ["barcelona", "espanha", "europa"] },
  { name: "Dubai", country: "Emirados Árabes", price: 3990, rating: 4.8, slug: "dubai", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=450&fit=crop", tags: ["dubai", "emirados", "oriente medio"] },
  { name: "Cancún", country: "México", price: 2890, rating: 4.5, slug: "cancun", image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&h=450&fit=crop", tags: ["cancun", "mexico", "caribe"] },
  { name: "Miami", country: "Estados Unidos", price: 2590, rating: 4.4, slug: "miami", image: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=600&h=450&fit=crop", tags: ["miami", "eua", "estados unidos", "america do norte"] },
  { name: "Buenos Aires", country: "Argentina", price: 990, rating: 4.5, slug: "buenos-aires", image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=600&h=450&fit=crop", tags: ["buenos aires", "argentina", "america do sul"] },
];

export const deals: Deal[] = [
  { id: 1, title: "Última Hora para Cancún", titleEn: "Last Minute to Cancún", description: "Resort all-inclusive, 5 noites", descriptionEn: "All-inclusive resort, 5 nights", price: 3490, originalPrice: 5490, image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&h=400&fit=crop", badge: "🔥 Oferta Quente", badgeEn: "🔥 Hot Deal", tags: ["cancun", "mexico", "caribe", "resort"] },
  { id: 2, title: "Fim de semana em Lisboa", titleEn: "Weekend in Lisbon", description: "Voo + Hotel, 3 noites", descriptionEn: "Flight + Hotel, 3 nights", price: 1790, originalPrice: 2790, image: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=600&h=400&fit=crop", badge: "⚡ Última Hora", badgeEn: "⚡ Last Minute", tags: ["lisboa", "portugal", "europa"] },
  { id: 3, title: "Cruzeiro pelo Caribe", titleEn: "Cruise to the Caribbean", description: "7 noites, todas as refeições incluídas", descriptionEn: "7-night cruise, all meals included", price: 4490, originalPrice: 6990, image: "https://images.unsplash.com/photo-1548574505-5e239809ee19?w=600&h=400&fit=crop", badge: "🚢 Temporada", badgeEn: "🚢 Seasonal", tags: ["caribe", "cruzeiro", "all inclusive"] },
  { id: 4, title: "Safari no Quênia", titleEn: "Safari in Kenya", description: "5 dias de aventura safari", descriptionEn: "5-day safari adventure", price: 6490, originalPrice: 9490, image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&h=400&fit=crop", badge: "🦁 Aventura", badgeEn: "🦁 Adventure", tags: ["quenia", "africa", "safari", "aventura"] },
  { id: 5, title: "Maldivas — Fuga Paradisíaca", titleEn: "Maldives Escape", description: "Villa sobre a água, 4 noites", descriptionEn: "Overwater villa, 4 nights", price: 7990, originalPrice: 12490, image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&h=400&fit=crop", badge: "💎 Luxo", badgeEn: "💎 Luxury", tags: ["maldivas", "asia", "luxo", "resort"] },
  { id: 6, title: "Bangkok & Phuket", titleEn: "Bangkok & Phuket", description: "Voo + 2 hotéis, 7 noites", descriptionEn: "Flight + 2 hotels, 7 nights", price: 3990, originalPrice: 5990, image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&h=400&fit=crop", badge: "✅ Melhor Valor", badgeEn: "✅ Best Value", tags: ["bangkok", "phuket", "tailandia", "asia"] },
  { id: 7, title: "Patagônia Argentina", titleEn: "Patagonia Argentina", description: "Trekking + Hotel, 6 noites", descriptionEn: "Trekking + Hotel, 6 nights", price: 4290, originalPrice: 6790, image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&h=400&fit=crop", badge: "🏔️ Natureza", badgeEn: "🏔️ Nature", tags: ["patagonia", "argentina", "america do sul", "trekking"] },
  { id: 8, title: "Santorini Romântica", titleEn: "Romantic Santorini", description: "Hotel com vista, 5 noites", descriptionEn: "Hotel with view, 5 nights", price: 3890, originalPrice: 5990, image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&h=400&fit=crop", badge: "💕 Romântico", badgeEn: "💕 Romantic", tags: ["santorini", "grecia", "europa", "romantico"] },
  { id: 9, title: "Machu Picchu & Cusco", titleEn: "Machu Picchu & Cusco", description: "Tour guiado, 5 noites", descriptionEn: "Guided tour, 5 nights", price: 3290, originalPrice: 5290, image: "https://images.unsplash.com/photo-1587595431973-160d0d163e70?w=600&h=400&fit=crop", badge: "🏛️ Histórico", badgeEn: "🏛️ Historical", tags: ["machu picchu", "cusco", "peru", "america do sul", "historia"] },
];

export const destinationDetails: Record<string, { name: string; country: string; image: string; description: string; descriptionEn: string; bestTime: string; experiences: string[]; experiencesEn: string[] }> = {
  paris: { name: "Paris", country: "França", image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=600&fit=crop", description: "A Cidade Luz cativa com marcos icônicos, gastronomia de classe mundial e romance atemporal.", descriptionEn: "The City of Light captivates with iconic landmarks, world-class cuisine, and timeless romance.", bestTime: "Abril a Junho, Setembro a Novembro", experiences: ["Torre Eiffel", "Museu do Louvre", "Montmartre", "Cruzeiro pelo Sena", "Palácio de Versalhes"], experiencesEn: ["Eiffel Tower", "Louvre Museum", "Montmartre", "Seine River Cruise", "Palace of Versailles"] },
  rio: { name: "Rio de Janeiro", country: "Brasil", image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1200&h=600&fit=crop", description: "Famoso por suas praias deslumbrantes, carnaval vibrante e o icônico Cristo Redentor.", descriptionEn: "Famous for its stunning beaches, vibrant carnival, and the iconic Christ the Redeemer statue.", bestTime: "Dezembro a Março", experiences: ["Cristo Redentor", "Praia de Copacabana", "Pão de Açúcar", "Carnaval", "Floresta da Tijuca"], experiencesEn: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Carnival", "Tijuca Forest"] },
  tokyo: { name: "Tokyo", country: "Japão", image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&h=600&fit=crop", description: "Uma mistura fascinante de tecnologia ultramoderna e tradição antiga.", descriptionEn: "A mesmerizing blend of ultra-modern technology and ancient tradition.", bestTime: "Março a Maio, Setembro a Novembro", experiences: ["Shibuya Crossing", "Templo Senso-ji", "Mercado Tsukiji", "Akihabara", "Monte Fuji"], experiencesEn: ["Shibuya Crossing", "Senso-ji Temple", "Tsukiji Market", "Akihabara", "Mount Fuji Day Trip"] },
  rome: { name: "Roma", country: "Itália", image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&h=600&fit=crop", description: "A Cidade Eterna é um museu vivo com ruínas antigas, arte renascentista e culinária incrível.", descriptionEn: "The Eternal City is a living museum with ancient ruins, Renaissance art, and incredible cuisine.", bestTime: "Abril a Junho, Setembro a Outubro", experiences: ["Coliseu", "Vaticano", "Fontana di Trevi", "Fórum Romano", "Trastevere"], experiencesEn: ["Colosseum", "Vatican City", "Trevi Fountain", "Roman Forum", "Trastevere"] },
  bali: { name: "Bali", country: "Indonésia", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&h=600&fit=crop", description: "Um paraíso tropical de terraços de arroz, templos sagrados e praias pristinas.", descriptionEn: "A tropical paradise of rice terraces, sacred temples, and pristine beaches.", bestTime: "Abril a Outubro", experiences: ["Terraços de Ubud", "Tanah Lot", "Uluwatu", "Seminyak Beach", "Monte Batur"], experiencesEn: ["Ubud Rice Terraces", "Tanah Lot Temple", "Uluwatu", "Seminyak Beach", "Mount Batur Sunrise Trek"] },
  "new-york": { name: "New York", country: "Estados Unidos", image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=600&fit=crop", description: "A cidade que nunca dorme pulsa com energia, cultura e marcos icônicos.", descriptionEn: "The city that never sleeps pulses with energy, culture, and iconic landmarks.", bestTime: "Abril a Junho, Setembro a Novembro", experiences: ["Estátua da Liberdade", "Central Park", "Times Square", "Brooklyn Bridge", "Metropolitan Museum"], experiencesEn: ["Statue of Liberty", "Central Park", "Times Square", "Brooklyn Bridge", "Metropolitan Museum"] },
  london: { name: "Londres", country: "Inglaterra", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop", description: "Uma metrópole vibrante que combina história milenar com cultura contemporânea.", descriptionEn: "A vibrant metropolis blending ancient history with contemporary culture.", bestTime: "Maio a Setembro", experiences: ["Big Ben", "Tower Bridge", "Palácio de Buckingham", "London Eye", "British Museum"], experiencesEn: ["Big Ben", "Tower Bridge", "Buckingham Palace", "London Eye", "British Museum"] },
  barcelona: { name: "Barcelona", country: "Espanha", image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&h=600&fit=crop", description: "A capital catalã encanta com a arquitetura de Gaudí, praias e culinária mediterrânea.", descriptionEn: "The Catalan capital enchants with Gaudí's architecture, beaches, and Mediterranean cuisine.", bestTime: "Maio a Junho, Setembro a Outubro", experiences: ["Sagrada Família", "Park Güell", "La Rambla", "Praia de Barceloneta", "Bairro Gótico"], experiencesEn: ["Sagrada Família", "Park Güell", "La Rambla", "Barceloneta Beach", "Gothic Quarter"] },
  dubai: { name: "Dubai", country: "Emirados Árabes", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=600&fit=crop", description: "Uma cidade futurista no deserto com arranha-céus impressionantes e luxo incomparável.", descriptionEn: "A futuristic desert city with breathtaking skyscrapers and unmatched luxury.", bestTime: "Novembro a Março", experiences: ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari", "Dubai Marina"], experiencesEn: ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari", "Dubai Marina"] },
  cancun: { name: "Cancún", country: "México", image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200&h=600&fit=crop", description: "Praias de areia branca, águas turquesa e ruínas maias em um destino paradisíaco.", descriptionEn: "White sand beaches, turquoise waters, and Mayan ruins in a paradise destination.", bestTime: "Dezembro a Abril", experiences: ["Chichén Itzá", "Isla Mujeres", "Xcaret", "Zona Hotelera", "Cenotes"], experiencesEn: ["Chichén Itzá", "Isla Mujeres", "Xcaret", "Hotel Zone", "Cenotes"] },
  miami: { name: "Miami", country: "Estados Unidos", image: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=1200&h=600&fit=crop", description: "South Beach, vida noturna vibrante, arte urbana e a energia latina de uma cidade única.", descriptionEn: "South Beach, vibrant nightlife, urban art, and the Latin energy of a unique city.", bestTime: "Março a Maio", experiences: ["South Beach", "Wynwood Walls", "Little Havana", "Key Biscayne", "Everglades"], experiencesEn: ["South Beach", "Wynwood Walls", "Little Havana", "Key Biscayne", "Everglades"] },
  "buenos-aires": { name: "Buenos Aires", country: "Argentina", image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=1200&h=600&fit=crop", description: "A Paris da América do Sul: tango, churrasco, arquitetura europeia e muita cultura.", descriptionEn: "The Paris of South America: tango, steak, European architecture, and rich culture.", bestTime: "Março a Maio, Setembro a Novembro", experiences: ["La Boca", "Recoleta", "Puerto Madero", "San Telmo", "Teatro Colón"], experiencesEn: ["La Boca", "Recoleta", "Puerto Madero", "San Telmo", "Teatro Colón"] },
};
