export interface EventPackage {
  id: string;
  event: string;
  location: string;
  country: string;
  countryCode: string;
  date: string;
  image: string;
  price: number;
  originalPrice: number;
  badge: string;
  flight: { from: string; airline: string };
  accommodation: { name: string; type: string; distance: string };
  tickets: { type: string; section: string };
  includes: string[];
  description: string;
  highlights: string[];
  touristSpots: string[];
  tags: string[];
}

export const eventPackages: EventPackage[] = [
  // === COPA DO MUNDO 2026 ===
  {
    id: "wc-2026-ny",
    event: "FIFA World Cup 2026 — Fase de Grupos",
    location: "New York / New Jersey",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Junho 2026",
    image: "https://upload.wikimedia.org/wikipedia/pt/thumb/e/e0/2026_FIFA_World_Cup_emblem.svg/400px-2026_FIFA_World_Cup_emblem.svg.png",
    price: 18490,
    originalPrice: 27990,
    badge: "⚽ Copa do Mundo",
    flight: { from: "São Paulo (GRU)", airline: "LATAM Airlines" },
    accommodation: { name: "Manhattan Loft perto do MetLife", type: "Airbnb", distance: "25 min do estádio" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "7 noites de hospedagem", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    description: "Viva a emoção da Copa do Mundo 2026 nos Estados Unidos! Pacote completo com voo direto de São Paulo, hospedagem em Manhattan e ingressos para jogos da fase de grupos no MetLife Stadium.",
    highlights: ["Estádio MetLife Stadium (82.500 lugares)", "Hospedagem em Manhattan com vista para NYC", "Guia turístico em português", "Kit torcedor exclusivo"],
    touristSpots: ["Estátua da Liberdade", "Central Park", "Times Square", "Brooklyn Bridge", "Empire State Building"],
    tags: ["copa", "futebol", "eua", "new york", "estados unidos", "world cup"],
  },
  {
    id: "wc-2026-miami",
    event: "FIFA World Cup 2026 — Miami",
    location: "Miami",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Junho 2026",
    image: "https://upload.wikimedia.org/wikipedia/pt/thumb/e/e0/2026_FIFA_World_Cup_emblem.svg/400px-2026_FIFA_World_Cup_emblem.svg.png",
    price: 16990,
    originalPrice: 25490,
    badge: "⚽ Copa do Mundo",
    flight: { from: "São Paulo (GRU)", airline: "GOL" },
    accommodation: { name: "Hotel South Beach", type: "Hotel 4★", distance: "20 min do Hard Rock Stadium" },
    tickets: { type: "Fase de Grupos", section: "Categoria 3" },
    includes: ["Voo ida e volta", "6 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    description: "Copa do Mundo 2026 em Miami! Jogos no Hard Rock Stadium com hospedagem em South Beach e toda a energia da cidade.",
    highlights: ["Hard Rock Stadium", "South Beach & Ocean Drive", "Brickell City Centre", "Noite em Wynwood"],
    touristSpots: ["South Beach", "Wynwood Walls", "Little Havana", "Key Biscayne", "Everglades"],
    tags: ["copa", "futebol", "eua", "miami", "estados unidos", "world cup"],
  },
  {
    id: "wc-2026-la",
    event: "FIFA World Cup 2026 — Los Angeles",
    location: "Los Angeles",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Junho 2026",
    image: "https://upload.wikimedia.org/wikipedia/pt/thumb/e/e0/2026_FIFA_World_Cup_emblem.svg/400px-2026_FIFA_World_Cup_emblem.svg.png",
    price: 19290,
    originalPrice: 28990,
    badge: "⚽ Copa do Mundo",
    flight: { from: "São Paulo (GRU)", airline: "LATAM Airlines" },
    accommodation: { name: "Apartamento Hollywood", type: "Airbnb", distance: "30 min do SoFi Stadium" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "7 noites de hospedagem", "2 ingressos", "Transfer aeroporto", "Seguro viagem", "Passeio por Hollywood"],
    description: "Assista à Copa do Mundo no incrível SoFi Stadium em Los Angeles! Pacote com hospedagem em Hollywood e tour pela cidade dos anjos.",
    highlights: ["SoFi Stadium — o mais moderno do mundo", "Passeio por Hollywood Boulevard", "Sunset Strip", "Venice Beach"],
    touristSpots: ["Hollywood Sign", "Santa Monica Pier", "Venice Beach", "Griffith Observatory", "Universal Studios"],
    tags: ["copa", "futebol", "eua", "los angeles", "estados unidos", "world cup"],
  },
  {
    id: "wc-2026-mexico",
    event: "FIFA World Cup 2026 — Cidade do México",
    location: "Cidade do México",
    country: "México",
    countryCode: "MX",
    date: "Junho 2026",
    image: "https://upload.wikimedia.org/wikipedia/pt/thumb/e/e0/2026_FIFA_World_Cup_emblem.svg/400px-2026_FIFA_World_Cup_emblem.svg.png",
    price: 12990,
    originalPrice: 19490,
    badge: "⚽ Copa do Mundo",
    flight: { from: "São Paulo (GRU)", airline: "Aeroméxico" },
    accommodation: { name: "Hotel Zona Rosa", type: "Hotel 4★", distance: "25 min do Azteca" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "6 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    description: "Copa do Mundo no lendário Estádio Azteca! Hospedagem na Zona Rosa e imersão na cultura mexicana.",
    highlights: ["Estádio Azteca — palco de 2 finais", "Zona Rosa & Condesa", "Gastronomia mexicana", "Cultura asteca"],
    touristSpots: ["Zócalo", "Museu Nacional de Antropologia", "Teotihuacán", "Coyoacán", "Chapultepec"],
    tags: ["copa", "futebol", "mexico", "world cup"],
  },
  {
    id: "wc-2026-toronto",
    event: "FIFA World Cup 2026 — Toronto",
    location: "Toronto",
    country: "Canadá",
    countryCode: "CA",
    date: "Junho 2026",
    image: "https://upload.wikimedia.org/wikipedia/pt/thumb/e/e0/2026_FIFA_World_Cup_emblem.svg/400px-2026_FIFA_World_Cup_emblem.svg.png",
    price: 17490,
    originalPrice: 26290,
    badge: "⚽ Copa do Mundo",
    flight: { from: "São Paulo (GRU)", airline: "Air Canada" },
    accommodation: { name: "Hotel Downtown Toronto", type: "Hotel 4★", distance: "15 min do BMO Field" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "6 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    description: "Copa do Mundo 2026 em Toronto! Explore a cidade mais multicultural do Canadá e vibre com o futebol.",
    highlights: ["BMO Field renovado", "CN Tower", "Distillery District", "Niagara Falls day trip"],
    touristSpots: ["CN Tower", "Royal Ontario Museum", "Niagara Falls", "Kensington Market", "Toronto Islands"],
    tags: ["copa", "futebol", "canada", "toronto", "world cup"],
  },
  {
    id: "wc-2026-final",
    event: "FIFA World Cup 2026 — Grande Final",
    location: "New York / New Jersey",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Julho 2026",
    image: "https://upload.wikimedia.org/wikipedia/pt/thumb/e/e0/2026_FIFA_World_Cup_emblem.svg/400px-2026_FIFA_World_Cup_emblem.svg.png",
    price: 36990,
    originalPrice: 52990,
    badge: "🏆 Grande Final",
    flight: { from: "São Paulo (GRU)", airline: "American Airlines" },
    accommodation: { name: "Hotel Luxo Times Square", type: "Hotel 5★", distance: "30 min do estádio" },
    tickets: { type: "Partida Final", section: "Categoria 1" },
    includes: ["Voo ida e volta", "5 noites hotel", "Ingresso da final", "Acesso lounge VIP", "Transfer aeroporto", "City tour"],
    description: "A experiência definitiva do futebol! Assista à final da Copa do Mundo 2026 com ingresso Categoria 1, hospedagem 5 estrelas na Times Square e acesso VIP exclusivo.",
    highlights: ["Ingresso Categoria 1 — próximo ao campo", "Hotel 5★ na Times Square", "Acesso ao Lounge VIP FIFA", "City tour por Nova York incluso"],
    touristSpots: ["Estátua da Liberdade", "Central Park", "Times Square", "Metropolitan Museum", "Broadway"],
    tags: ["copa", "futebol", "eua", "new york", "estados unidos", "world cup", "final"],
  },

  // === OLIMPÍADAS 2028 ===
  {
    id: "olympics-2028",
    event: "Jogos Olímpicos 2028",
    location: "Los Angeles",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Julho 2028",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/2028_Summer_Olympics_logo.svg/400px-2028_Summer_Olympics_logo.svg.png",
    price: 22690,
    originalPrice: 34290,
    badge: "🏅 Olimpíadas",
    flight: { from: "São Paulo (GRU)", airline: "Delta Airlines" },
    accommodation: { name: "Apartamento Santa Monica Beach", type: "Airbnb", distance: "20 min dos locais" },
    tickets: { type: "Passe Multi-Eventos", section: "3 eventos incluídos" },
    includes: ["Voo ida e volta", "10 noites de hospedagem", "3 ingressos de eventos", "Passe de metrô", "Seguro viagem"],
    description: "Los Angeles 2028! Assista a 3 modalidades olímpicas, fique em apartamento na praia de Santa Monica e explore a Cidade dos Anjos com passe de metrô incluso.",
    highlights: ["3 modalidades olímpicas à escolha", "Apartamento à beira-mar em Santa Monica", "Passe de metrô ilimitado", "Roteiro turístico por Hollywood"],
    touristSpots: ["Hollywood Sign", "Venice Beach", "Getty Center", "Griffith Observatory", "Rodeo Drive"],
    tags: ["olimpiadas", "olympics", "eua", "los angeles", "estados unidos", "esporte"],
  },

  // === FÓRMULA 1 ===
  {
    id: "f1-monaco-2026",
    event: "F1 Grand Prix Monaco",
    location: "Monte Carlo",
    country: "Mônaco",
    countryCode: "MC",
    date: "Maio 2026",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/400px-F1.svg.png",
    price: 25290,
    originalPrice: 36990,
    badge: "🏎️ Fórmula 1",
    flight: { from: "São Paulo (GRU)", airline: "Air France" },
    accommodation: { name: "Apartamento Riviera em Nice", type: "Airbnb", distance: "30 min do circuito" },
    tickets: { type: "Dia da Corrida", section: "Tribuna K" },
    includes: ["Voo ida e volta", "5 noites de hospedagem", "Ingresso dia da corrida", "Pit lane walk", "Transfer aeroporto"],
    description: "Sinta a velocidade do GP de Mônaco! Hospedagem na Riviera Francesa, ingresso para o dia da corrida com acesso ao Pit Lane e a atmosfera glamourosa de Monte Carlo.",
    highlights: ["Circuito de rua mais famoso do mundo", "Acesso ao Pit Lane Walk", "Hospedagem na Côte d'Azur", "Passeio de barco pelo porto de Mônaco"],
    touristSpots: ["Casino de Monte Carlo", "Palácio do Príncipe", "Nice Promenade des Anglais", "Cannes", "Saint-Tropez"],
    tags: ["f1", "formula 1", "monaco", "europa", "corrida", "automobilismo"],
  },
  {
    id: "f1-interlagos-2026",
    event: "F1 GP de São Paulo",
    location: "São Paulo",
    country: "Brasil",
    countryCode: "BR",
    date: "Novembro 2026",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/400px-F1.svg.png",
    price: 4990,
    originalPrice: 7990,
    badge: "🏎️ Fórmula 1",
    flight: { from: "Rio de Janeiro (GIG)", airline: "GOL" },
    accommodation: { name: "Hotel Faria Lima", type: "Hotel 4★", distance: "20 min de Interlagos" },
    tickets: { type: "Dia da Corrida", section: "Arquibancada A" },
    includes: ["Voo ida e volta", "3 noites hotel", "Ingresso da corrida", "Transfer aeroporto"],
    description: "GP de São Paulo em Interlagos! O autódromo mais emocionante do calendário da F1, com curvas icônicas e a paixão brasileira pelo automobilismo.",
    highlights: ["Autódromo de Interlagos", "Subida do S do Senna", "Gastronomia paulistana", "Vida noturna em SP"],
    touristSpots: ["Avenida Paulista", "Parque Ibirapuera", "MASP", "Beco do Batman", "Mercado Municipal"],
    tags: ["f1", "formula 1", "brasil", "são paulo", "corrida", "automobilismo"],
  },

  // === SUPER BOWL ===
  {
    id: "superbowl-2027",
    event: "Super Bowl LXI",
    location: "Los Angeles",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Fevereiro 2027",
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/National_Football_League_logo.svg/400px-National_Football_League_logo.svg.png",
    price: 28990,
    originalPrice: 42290,
    badge: "🏈 Super Bowl",
    flight: { from: "São Paulo (GRU)", airline: "United Airlines" },
    accommodation: { name: "Hotel Downtown LA", type: "Hotel 4★", distance: "15 min do SoFi Stadium" },
    tickets: { type: "Super Bowl", section: "Upper Level" },
    includes: ["Voo ida e volta", "4 noites hotel", "Ingresso do jogo", "Tailgate pré-jogo", "Transfer aeroporto"],
    description: "O maior espetáculo do esporte americano! Ingresso para o Super Bowl LXI no SoFi Stadium, com tailgate party exclusiva e hotel 4 estrelas em Downtown LA.",
    highlights: ["Ingresso Super Bowl LXI", "Tailgate Party com churrasco americano", "SoFi Stadium — o mais moderno do mundo", "Noite em Hollywood inclusa"],
    touristSpots: ["Hollywood Boulevard", "Santa Monica Pier", "Beverly Hills", "Malibu", "Disneyland"],
    tags: ["super bowl", "nfl", "eua", "los angeles", "estados unidos", "futebol americano"],
  },

  // === CHAMPIONS LEAGUE ===
  {
    id: "champions-league-2026",
    event: "Final da UEFA Champions League",
    location: "Munique",
    country: "Alemanha",
    countryCode: "DE",
    date: "Maio 2026",
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/UEFA_Champions_League_logo_2024.svg/400px-UEFA_Champions_League_logo_2024.svg.png",
    price: 21090,
    originalPrice: 30590,
    badge: "⚽ Champions",
    flight: { from: "São Paulo (GRU)", airline: "Lufthansa" },
    accommodation: { name: "Flat no Centro de Munique", type: "Airbnb", distance: "20 min da Allianz Arena" },
    tickets: { type: "Partida Final", section: "Categoria 2" },
    includes: ["Voo ida e volta", "4 noites de hospedagem", "Ingresso da final", "Acesso fan zone", "Transfer aeroporto"],
    description: "A final da Champions League em Munique! Ingresso para a decisão na Allianz Arena, hospedagem no centro da cidade e acesso à Fan Zone oficial da UEFA.",
    highlights: ["Allianz Arena — um dos estádios mais icônicos", "Fan Zone oficial da UEFA", "Tour por cervejarias de Munique", "Hospedagem no coração da cidade"],
    touristSpots: ["Marienplatz", "Englischer Garten", "BMW Museum", "Nymphenburg Palace", "Hofbräuhaus"],
    tags: ["champions", "futebol", "alemanha", "munique", "europa", "uefa"],
  },

  // === WIMBLEDON ===
  {
    id: "wimbledon-2026",
    event: "Wimbledon 2026",
    location: "Londres",
    country: "Inglaterra",
    countryCode: "GB",
    date: "Julho 2026",
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Wimbledon.svg/400px-Wimbledon.svg.png",
    price: 17390,
    originalPrice: 25890,
    badge: "🎾 Tênis",
    flight: { from: "São Paulo (GRU)", airline: "British Airways" },
    accommodation: { name: "B&B em Wimbledon Village", type: "B&B", distance: "10 min a pé das quadras" },
    tickets: { type: "Centre Court", section: "Debenture Seat" },
    includes: ["Voo ida e volta", "5 noites de hospedagem", "2 day passes", "Experiência Strawberries & Cream", "Transfer aeroporto"],
    description: "O torneio de tênis mais prestigiado do mundo! Ingresso para o Centre Court, hospedagem charmosa em Wimbledon Village e a clássica experiência com morangos com creme.",
    highlights: ["Centre Court — Debenture Seat premium", "Wimbledon Village — charme inglês", "Afternoon tea no All England Club", "Tour por Londres incluído"],
    touristSpots: ["Big Ben", "Tower Bridge", "Buckingham Palace", "London Eye", "British Museum"],
    tags: ["wimbledon", "tenis", "inglaterra", "londres", "europa"],
  },

  // === CARNAVAL ===
  {
    id: "carnival-rio-2027",
    event: "Carnaval do Rio 2027",
    location: "Rio de Janeiro",
    country: "Brasil",
    countryCode: "BR",
    date: "Fevereiro 2027",
    image: "https://images.unsplash.com/photo-1551887196-72e32bfc7bf3?w=800&h=500&fit=crop",
    price: 4990,
    originalPrice: 7490,
    badge: "🎭 Carnaval",
    flight: { from: "São Paulo (GRU)", airline: "GOL" },
    accommodation: { name: "Copacabana Beira-Mar", type: "Hotel 4★", distance: "5 min do Sambódromo" },
    tickets: { type: "Sambódromo", section: "Setor 9 - Arquibancada" },
    includes: ["Voo ida e volta", "5 noites hotel", "Ingresso Sambódromo", "Guia de blocos", "Transfer aeroporto"],
    description: "O maior carnaval do planeta! Assista aos desfiles no Sambódromo, fique em hotel beira-mar em Copacabana e viva a energia dos blocos de rua do Rio.",
    highlights: ["Desfiles das escolas de samba campeãs", "Hotel frente ao mar em Copacabana", "Guia completo dos blocos de rua", "Passeio pelo Cristo Redentor"],
    touristSpots: ["Cristo Redentor", "Pão de Açúcar", "Copacabana", "Ipanema", "Lapa"],
    tags: ["carnaval", "brasil", "rio de janeiro", "festa", "cultura"],
  },

  // === NBA ===
  {
    id: "nba-finals-2027",
    event: "NBA Finals 2027",
    location: "A definir",
    country: "Estados Unidos",
    countryCode: "US",
    date: "Junho 2027",
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/National_Basketball_Association_logo.svg/400px-National_Basketball_Association_logo.svg.png",
    price: 24990,
    originalPrice: 37490,
    badge: "🏀 NBA",
    flight: { from: "São Paulo (GRU)", airline: "American Airlines" },
    accommodation: { name: "Hotel próximo à arena", type: "Hotel 4★", distance: "10 min da arena" },
    tickets: { type: "NBA Finals", section: "Upper Bowl" },
    includes: ["Voo ida e volta", "5 noites hotel", "Ingresso Game 1", "Tour pela arena", "Transfer aeroporto"],
    description: "Viva a emoção das finais da NBA! Ingresso para assistir aos melhores jogadores de basquete do planeta em ação, com hospedagem 4 estrelas.",
    highlights: ["Ingresso NBA Finals", "Tour pela arena oficial", "NBA Store exclusiva", "Experiência de jogo autêntica americana"],
    touristSpots: ["NBA Store", "Basketball Hall of Fame", "Arena oficial NBA", "Centro da cidade-sede"],
    tags: ["nba", "basquete", "eua", "estados unidos", "esporte"],
  },

  // === ROCK IN RIO ===
  {
    id: "rock-in-rio-2026",
    event: "Rock in Rio 2026",
    location: "Rio de Janeiro",
    country: "Brasil",
    countryCode: "BR",
    date: "Setembro 2026",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop",
    price: 3990,
    originalPrice: 5990,
    badge: "🎸 Festival",
    flight: { from: "São Paulo (GRU)", airline: "LATAM Airlines" },
    accommodation: { name: "Hotel Barra da Tijuca", type: "Hotel 3★", distance: "10 min do Parque Olímpico" },
    tickets: { type: "Rock in Rio", section: "Pista Premium — 2 dias" },
    includes: ["Voo ida e volta", "4 noites hotel", "2 ingressos Rock in Rio", "Transfer aeroporto"],
    description: "O maior festival de música da América Latina! 2 dias de Rock in Rio com hospedagem na Barra da Tijuca e transporte incluso.",
    highlights: ["2 dias de festival", "Palco Mundo", "Artistas internacionais", "Gastronomia no festival"],
    touristSpots: ["Cristo Redentor", "Praia de Copacabana", "Pão de Açúcar", "Jardim Botânico", "Lagoa Rodrigo de Freitas"],
    tags: ["rock in rio", "festival", "musica", "brasil", "rio de janeiro"],
  },

  // === ROLAND GARROS ===
  {
    id: "roland-garros-2026",
    event: "Roland Garros 2026",
    location: "Paris",
    country: "França",
    countryCode: "FR",
    date: "Junho 2026",
    image: "https://images.unsplash.com/photo-1499510318569-1a3d67dc3976?w=800&h=500&fit=crop",
    price: 15990,
    originalPrice: 23490,
    badge: "🎾 Tênis",
    flight: { from: "São Paulo (GRU)", airline: "Air France" },
    accommodation: { name: "Hotel Saint-Germain", type: "Hotel 4★", distance: "15 min de Roland Garros" },
    tickets: { type: "Quartas de Final", section: "Philippe-Chatrier" },
    includes: ["Voo ida e volta", "5 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    description: "O saibro mais famoso do mundo! Assista às quartas de final em Roland Garros e desfrute de Paris no verão europeu.",
    highlights: ["Court Philippe-Chatrier", "Gastronomia francesa no torneio", "Paris no verão", "Tour guiado por Paris"],
    touristSpots: ["Torre Eiffel", "Louvre", "Montmartre", "Champs-Élysées", "Notre-Dame"],
    tags: ["roland garros", "tenis", "paris", "franca", "europa"],
  },
];
