import olympics2028Img from "@/assets/events/olympics-2028.png";
import f1Interlagos2026Img from "@/assets/events/f1-interlagos-2026.png";
import f1Monaco2026Img from "@/assets/events/f1-monaco-2026.png";
import carnivalRio2027Img from "@/assets/events/carnival-rio-2027.png";
import oktoberfest2026Img from "@/assets/events/oktoberfest-2026.png";
import cannes2027Img from "@/assets/events/cannes-2027.png";
import diaMuertos2026Img from "@/assets/events/dia-muertos-2026.png";
import holiIndia2027Img from "@/assets/events/holi-india-2027.png";
import tomorrowland2026Img from "@/assets/events/tomorrowland-2026.png";
import vendimia2027Img from "@/assets/events/vendimia-2027.png";
import wcTorontoImg from "@/assets/events/wc-toronto.png";
import wcNyGroupImg from "@/assets/events/wc-ny-group.png";
import wcMexicoImg from "@/assets/events/wc-mexico.png";
import wcMiamiImg from "@/assets/events/wc-miami.png";

export interface EventPackage {
  id: string;
  event: string;
  eventEn: string;
  location: string;
  country: string;
  countryEn: string;
  countryCode: string;
  date: string;
  dateEn: string;
  image: string;
  price: number;
  originalPrice: number;
  badge: string;
  category: string;
  flight: { from: string; fromCode: string; toCode: string; airline: string };
  accommodation: { name: string; type: string; distance: string };
  tickets: { type: string; section: string };
  includes: string[];
  includesEn: string[];
  description: string;
  descriptionEn: string;
  highlights: string[];
  highlightsEn: string[];
  touristSpots: string[];
  tags: string[];
}

export const eventPackages: EventPackage[] = [
  // === COPA DO MUNDO 2026 ===
  {
    id: "wc-2026-ny",
    event: "FIFA World Cup 2026 — Fase de Grupos",
    eventEn: "FIFA World Cup 2026 — Group Stage",
    location: "New York / New Jersey",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Junho 2026",
    dateEn: "June 2026",
    image: wcNyGroupImg,
    price: 18490,
    originalPrice: 27990,
    badge: "⚽ Copa do Mundo",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "JFK", airline: "LATAM Airlines" },
    accommodation: { name: "Manhattan Loft perto do MetLife", type: "Airbnb", distance: "25 min do estádio" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "7 noites de hospedagem", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "7 nights accommodation", "2 tickets", "Airport transfer", "Travel insurance"],
    description: "Viva a emoção da Copa do Mundo 2026 nos Estados Unidos! Pacote completo com voo direto de São Paulo, hospedagem em Manhattan e ingressos para jogos da fase de grupos no MetLife Stadium.",
    descriptionEn: "Experience the thrill of the 2026 World Cup in the US! Complete package with direct flight from São Paulo, Manhattan accommodation and group stage tickets at MetLife Stadium.",
    highlights: ["Estádio MetLife Stadium (82.500 lugares)", "Hospedagem em Manhattan com vista para NYC", "Guia turístico em português", "Kit torcedor exclusivo"],
    highlightsEn: ["MetLife Stadium (82,500 seats)", "Manhattan accommodation with NYC views", "Portuguese-speaking guide", "Exclusive fan kit"],
    touristSpots: ["Estátua da Liberdade", "Central Park", "Times Square", "Brooklyn Bridge", "Empire State Building"],
    tags: ["copa", "futebol", "eua", "new york", "estados unidos", "world cup", "football"],
  },
  {
    id: "wc-2026-miami",
    event: "FIFA World Cup 2026 — Miami",
    eventEn: "FIFA World Cup 2026 — Miami",
    location: "Miami",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Junho 2026",
    dateEn: "June 2026",
    image: wcMiamiImg,
    price: 16990,
    originalPrice: 25490,
    badge: "⚽ Copa do Mundo",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MIA", airline: "GOL" },
    accommodation: { name: "Hotel South Beach", type: "Hotel 4★", distance: "20 min do Hard Rock Stadium" },
    tickets: { type: "Fase de Grupos", section: "Categoria 3" },
    includes: ["Voo ida e volta", "6 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "6 nights hotel", "2 tickets", "Airport transfer", "Travel insurance"],
    description: "Copa do Mundo 2026 em Miami! Jogos no Hard Rock Stadium com hospedagem em South Beach e toda a energia da cidade.",
    descriptionEn: "World Cup 2026 in Miami! Games at Hard Rock Stadium with South Beach accommodation and all the city's energy.",
    highlights: ["Hard Rock Stadium", "South Beach & Ocean Drive", "Brickell City Centre", "Noite em Wynwood"],
    highlightsEn: ["Hard Rock Stadium", "South Beach & Ocean Drive", "Brickell City Centre", "Wynwood night out"],
    touristSpots: ["South Beach", "Wynwood Walls", "Little Havana", "Key Biscayne", "Everglades"],
    tags: ["copa", "futebol", "eua", "miami", "estados unidos", "world cup", "football"],
  },
  {
    id: "wc-2026-la",
    event: "FIFA World Cup 2026 — Los Angeles",
    eventEn: "FIFA World Cup 2026 — Los Angeles",
    location: "Los Angeles",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Junho 2026",
    dateEn: "June 2026",
    image: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&h=500&fit=crop",
    price: 19290,
    originalPrice: 28990,
    badge: "⚽ Copa do Mundo",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "LAX", airline: "LATAM Airlines" },
    accommodation: { name: "Apartamento Hollywood", type: "Airbnb", distance: "30 min do SoFi Stadium" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "7 noites de hospedagem", "2 ingressos", "Transfer aeroporto", "Seguro viagem", "Passeio por Hollywood"],
    includesEn: ["Round-trip flight", "7 nights accommodation", "2 tickets", "Airport transfer", "Travel insurance", "Hollywood tour"],
    description: "Assista à Copa do Mundo no incrível SoFi Stadium em Los Angeles! Pacote com hospedagem em Hollywood e tour pela cidade dos anjos.",
    descriptionEn: "Watch the World Cup at the incredible SoFi Stadium in LA! Package with Hollywood accommodation and City of Angels tour.",
    highlights: ["SoFi Stadium — o mais moderno do mundo", "Passeio por Hollywood Boulevard", "Sunset Strip", "Venice Beach"],
    highlightsEn: ["SoFi Stadium — most modern in the world", "Hollywood Boulevard tour", "Sunset Strip", "Venice Beach"],
    touristSpots: ["Hollywood Sign", "Santa Monica Pier", "Venice Beach", "Griffith Observatory", "Universal Studios"],
    tags: ["copa", "futebol", "eua", "los angeles", "estados unidos", "world cup", "football"],
  },
  {
    id: "wc-2026-mexico",
    event: "FIFA World Cup 2026 — Cidade do México",
    eventEn: "FIFA World Cup 2026 — Mexico City",
    location: "Cidade do México",
    country: "México",
    countryEn: "Mexico",
    countryCode: "MX",
    date: "Junho 2026",
    dateEn: "June 2026",
    image: wcMexicoImg,
    price: 12990,
    originalPrice: 19490,
    badge: "⚽ Copa do Mundo",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MEX", airline: "Aeroméxico" },
    accommodation: { name: "Hotel Zona Rosa", type: "Hotel 4★", distance: "25 min do Azteca" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "6 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "6 nights hotel", "2 tickets", "Airport transfer", "Travel insurance"],
    description: "Copa do Mundo no lendário Estádio Azteca! Hospedagem na Zona Rosa e imersão na cultura mexicana.",
    descriptionEn: "World Cup at the legendary Azteca Stadium! Accommodation in Zona Rosa and immersion in Mexican culture.",
    highlights: ["Estádio Azteca — palco de 2 finais", "Zona Rosa & Condesa", "Gastronomia mexicana", "Cultura asteca"],
    highlightsEn: ["Azteca Stadium — host of 2 finals", "Zona Rosa & Condesa", "Mexican gastronomy", "Aztec culture"],
    touristSpots: ["Zócalo", "Museu Nacional de Antropologia", "Teotihuacán", "Coyoacán", "Chapultepec"],
    tags: ["copa", "futebol", "mexico", "world cup", "football"],
  },
  {
    id: "wc-2026-toronto",
    event: "FIFA World Cup 2026 — Toronto",
    eventEn: "FIFA World Cup 2026 — Toronto",
    location: "Toronto",
    country: "Canadá",
    countryEn: "Canada",
    countryCode: "CA",
    date: "Junho 2026",
    dateEn: "June 2026",
    image: wcTorontoImg,
    price: 17490,
    originalPrice: 26290,
    badge: "⚽ Copa do Mundo",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "YYZ", airline: "Air Canada" },
    accommodation: { name: "Hotel Downtown Toronto", type: "Hotel 4★", distance: "15 min do BMO Field" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "6 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "6 nights hotel", "2 tickets", "Airport transfer", "Travel insurance"],
    description: "Copa do Mundo 2026 em Toronto! Explore a cidade mais multicultural do Canadá e vibre com o futebol.",
    descriptionEn: "World Cup 2026 in Toronto! Explore Canada's most multicultural city and feel the football vibe.",
    highlights: ["BMO Field renovado", "CN Tower", "Distillery District", "Niagara Falls day trip"],
    highlightsEn: ["Renovated BMO Field", "CN Tower", "Distillery District", "Niagara Falls day trip"],
    touristSpots: ["CN Tower", "Royal Ontario Museum", "Niagara Falls", "Kensington Market", "Toronto Islands"],
    tags: ["copa", "futebol", "canada", "toronto", "world cup", "football"],
  },
  {
    id: "wc-2026-final",
    event: "FIFA World Cup 2026 — Grande Final",
    eventEn: "FIFA World Cup 2026 — Grand Final",
    location: "New York / New Jersey",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Julho 2026",
    dateEn: "July 2026",
    image: "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&h=500&fit=crop",
    price: 36990,
    originalPrice: 52990,
    badge: "🏆 Grande Final",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "JFK", airline: "American Airlines" },
    accommodation: { name: "Hotel Luxo Times Square", type: "Hotel 5★", distance: "30 min do estádio" },
    tickets: { type: "Partida Final", section: "Categoria 1" },
    includes: ["Voo ida e volta", "5 noites hotel", "Ingresso da final", "Acesso lounge VIP", "Transfer aeroporto", "City tour"],
    includesEn: ["Round-trip flight", "5 nights hotel", "Final match ticket", "VIP lounge access", "Airport transfer", "City tour"],
    description: "A experiência definitiva do futebol! Assista à final da Copa do Mundo 2026 com ingresso Categoria 1, hospedagem 5 estrelas na Times Square e acesso VIP exclusivo.",
    descriptionEn: "The ultimate football experience! Watch the 2026 World Cup final with Category 1 ticket, 5-star Times Square hotel and exclusive VIP access.",
    highlights: ["Ingresso Categoria 1 — próximo ao campo", "Hotel 5★ na Times Square", "Acesso ao Lounge VIP FIFA", "City tour por Nova York incluso"],
    highlightsEn: ["Category 1 ticket — near the field", "5★ Hotel in Times Square", "FIFA VIP Lounge access", "NYC city tour included"],
    touristSpots: ["Estátua da Liberdade", "Central Park", "Times Square", "Metropolitan Museum", "Broadway"],
    tags: ["copa", "futebol", "eua", "new york", "estados unidos", "world cup", "final", "football"],
  },

  // === OLIMPÍADAS 2028 ===
  {
    id: "olympics-2028",
    event: "Jogos Olímpicos 2028",
    eventEn: "2028 Olympic Games",
    location: "Los Angeles",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Julho 2028",
    dateEn: "July 2028",
    image: olympics2028Img,
    price: 22690,
    originalPrice: 34290,
    badge: "🏅 Olimpíadas",
    category: "olympics",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "LAX", airline: "Delta Airlines" },
    accommodation: { name: "Apartamento Santa Monica Beach", type: "Airbnb", distance: "20 min dos locais" },
    tickets: { type: "Passe Multi-Eventos", section: "3 eventos incluídos" },
    includes: ["Voo ida e volta", "10 noites de hospedagem", "3 ingressos de eventos", "Passe de metrô", "Seguro viagem"],
    includesEn: ["Round-trip flight", "10 nights accommodation", "3 event tickets", "Metro pass", "Travel insurance"],
    description: "Los Angeles 2028! Assista a 3 modalidades olímpicas, fique em apartamento na praia de Santa Monica e explore a Cidade dos Anjos com passe de metrô incluso.",
    descriptionEn: "Los Angeles 2028! Watch 3 Olympic events, stay at a Santa Monica beach apartment and explore the City of Angels with included metro pass.",
    highlights: ["3 modalidades olímpicas à escolha", "Apartamento à beira-mar em Santa Monica", "Passe de metrô ilimitado", "Roteiro turístico por Hollywood"],
    highlightsEn: ["3 Olympic events of your choice", "Beachfront apartment in Santa Monica", "Unlimited metro pass", "Hollywood sightseeing tour"],
    touristSpots: ["Hollywood Sign", "Venice Beach", "Getty Center", "Griffith Observatory", "Rodeo Drive"],
    tags: ["olimpiadas", "olympics", "eua", "los angeles", "estados unidos", "esporte", "sport"],
  },

  // === FÓRMULA 1 ===
  {
    id: "f1-monaco-2026",
    event: "F1 Grand Prix Monaco",
    eventEn: "F1 Monaco Grand Prix",
    location: "Monte Carlo",
    country: "Mônaco",
    countryEn: "Monaco",
    countryCode: "MC",
    date: "Maio 2026",
    dateEn: "May 2026",
    image: f1Monaco2026Img,
    price: 25290,
    originalPrice: 36990,
    badge: "🏎️ Fórmula 1",
    category: "f1",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "NCE", airline: "Air France" },
    accommodation: { name: "Apartamento Riviera em Nice", type: "Airbnb", distance: "30 min do circuito" },
    tickets: { type: "Dia da Corrida", section: "Tribuna K" },
    includes: ["Voo ida e volta", "5 noites de hospedagem", "Ingresso dia da corrida", "Pit lane walk", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights accommodation", "Race day ticket", "Pit lane walk", "Airport transfer"],
    description: "Sinta a velocidade do GP de Mônaco! Hospedagem na Riviera Francesa, ingresso para o dia da corrida com acesso ao Pit Lane e a atmosfera glamourosa de Monte Carlo.",
    descriptionEn: "Feel the speed of the Monaco GP! French Riviera accommodation, race day ticket with Pit Lane access and the glamorous Monte Carlo atmosphere.",
    highlights: ["Circuito de rua mais famoso do mundo", "Acesso ao Pit Lane Walk", "Hospedagem na Côte d'Azur", "Passeio de barco pelo porto de Mônaco"],
    highlightsEn: ["Most famous street circuit in the world", "Pit Lane Walk access", "Côte d'Azur accommodation", "Boat tour of Monaco harbor"],
    touristSpots: ["Casino de Monte Carlo", "Palácio do Príncipe", "Nice Promenade des Anglais", "Cannes", "Saint-Tropez"],
    tags: ["f1", "formula 1", "monaco", "europa", "corrida", "automobilismo", "racing"],
  },
  {
    id: "f1-interlagos-2026",
    event: "F1 GP de São Paulo",
    eventEn: "F1 São Paulo Grand Prix",
    location: "São Paulo",
    country: "Brasil",
    countryEn: "Brazil",
    countryCode: "BR",
    date: "Novembro 2026",
    dateEn: "November 2026",
    image: f1Interlagos2026Img,
    price: 4990,
    originalPrice: 7990,
    badge: "🏎️ Fórmula 1",
    category: "f1",
    flight: { from: "Rio de Janeiro (GIG)", fromCode: "GIG", toCode: "GRU", airline: "GOL" },
    accommodation: { name: "Hotel Faria Lima", type: "Hotel 4★", distance: "20 min de Interlagos" },
    tickets: { type: "Dia da Corrida", section: "Arquibancada A" },
    includes: ["Voo ida e volta", "3 noites hotel", "Ingresso da corrida", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "3 nights hotel", "Race ticket", "Airport transfer"],
    description: "GP de São Paulo em Interlagos! O autódromo mais emocionante do calendário da F1, com curvas icônicas e a paixão brasileira pelo automobilismo.",
    descriptionEn: "São Paulo GP at Interlagos! The most exciting track on the F1 calendar, with iconic corners and Brazilian passion for motorsport.",
    highlights: ["Autódromo de Interlagos", "Subida do S do Senna", "Gastronomia paulistana", "Vida noturna em SP"],
    highlightsEn: ["Interlagos Circuit", "Senna's S turn", "São Paulo gastronomy", "SP nightlife"],
    touristSpots: ["Avenida Paulista", "Parque Ibirapuera", "MASP", "Beco do Batman", "Mercado Municipal"],
    tags: ["f1", "formula 1", "brasil", "são paulo", "corrida", "automobilismo", "racing"],
  },

  // === SUPER BOWL ===
  {
    id: "superbowl-2027",
    event: "Super Bowl LXI",
    eventEn: "Super Bowl LXI",
    location: "Los Angeles",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Fevereiro 2027",
    dateEn: "February 2027",
    image: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800&h=500&fit=crop",
    price: 28990,
    originalPrice: 42290,
    badge: "🏈 Super Bowl",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "LAX", airline: "United Airlines" },
    accommodation: { name: "Hotel Downtown LA", type: "Hotel 4★", distance: "15 min do SoFi Stadium" },
    tickets: { type: "Super Bowl", section: "Upper Level" },
    includes: ["Voo ida e volta", "4 noites hotel", "Ingresso do jogo", "Tailgate pré-jogo", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "4 nights hotel", "Game ticket", "Pre-game tailgate", "Airport transfer"],
    description: "O maior espetáculo do esporte americano! Ingresso para o Super Bowl LXI no SoFi Stadium, com tailgate party exclusiva e hotel 4 estrelas em Downtown LA.",
    descriptionEn: "The biggest spectacle in American sports! Super Bowl LXI ticket at SoFi Stadium, with exclusive tailgate party and 4-star Downtown LA hotel.",
    highlights: ["Ingresso Super Bowl LXI", "Tailgate Party com churrasco americano", "SoFi Stadium — o mais moderno do mundo", "Noite em Hollywood inclusa"],
    highlightsEn: ["Super Bowl LXI ticket", "Tailgate Party with American BBQ", "SoFi Stadium — most modern in the world", "Hollywood night out included"],
    touristSpots: ["Hollywood Boulevard", "Santa Monica Pier", "Beverly Hills", "Malibu", "Disneyland"],
    tags: ["super bowl", "nfl", "eua", "los angeles", "estados unidos", "futebol americano", "football"],
  },

  // === CHAMPIONS LEAGUE ===
  {
    id: "champions-league-2026",
    event: "Final da UEFA Champions League",
    eventEn: "UEFA Champions League Final",
    location: "Munique",
    country: "Alemanha",
    countryEn: "Germany",
    countryCode: "DE",
    date: "Maio 2026",
    dateEn: "May 2026",
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=500&fit=crop",
    price: 21090,
    originalPrice: 30590,
    badge: "⚽ Champions",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MUC", airline: "Lufthansa" },
    accommodation: { name: "Flat no Centro de Munique", type: "Airbnb", distance: "20 min da Allianz Arena" },
    tickets: { type: "Partida Final", section: "Categoria 2" },
    includes: ["Voo ida e volta", "4 noites de hospedagem", "Ingresso da final", "Acesso fan zone", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "4 nights accommodation", "Final match ticket", "Fan zone access", "Airport transfer"],
    description: "A final da Champions League em Munique! Ingresso para a decisão na Allianz Arena, hospedagem no centro da cidade e acesso à Fan Zone oficial da UEFA.",
    descriptionEn: "Champions League Final in Munich! Ticket for the final at Allianz Arena, city center accommodation and access to the official UEFA Fan Zone.",
    highlights: ["Allianz Arena — um dos estádios mais icônicos", "Fan Zone oficial da UEFA", "Tour por cervejarias de Munique", "Hospedagem no coração da cidade"],
    highlightsEn: ["Allianz Arena — one of the most iconic stadiums", "Official UEFA Fan Zone", "Munich brewery tour", "City center accommodation"],
    touristSpots: ["Marienplatz", "Englischer Garten", "BMW Museum", "Nymphenburg Palace", "Hofbräuhaus"],
    tags: ["champions", "futebol", "alemanha", "munique", "europa", "uefa", "football"],
  },

  // === WIMBLEDON ===
  {
    id: "wimbledon-2026",
    event: "Wimbledon 2026",
    eventEn: "Wimbledon 2026",
    location: "Londres",
    country: "Inglaterra",
    countryEn: "England",
    countryCode: "GB",
    date: "Julho 2026",
    dateEn: "July 2026",
    image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&h=500&fit=crop",
    price: 17390,
    originalPrice: 25890,
    badge: "🎾 Tênis",
    category: "tennis",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "LHR", airline: "British Airways" },
    accommodation: { name: "B&B em Wimbledon Village", type: "B&B", distance: "10 min a pé das quadras" },
    tickets: { type: "Centre Court", section: "Debenture Seat" },
    includes: ["Voo ida e volta", "5 noites de hospedagem", "2 day passes", "Experiência Strawberries & Cream", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights accommodation", "2 day passes", "Strawberries & Cream experience", "Airport transfer"],
    description: "O torneio de tênis mais prestigiado do mundo! Ingresso para o Centre Court, hospedagem charmosa em Wimbledon Village e a clássica experiência com morangos com creme.",
    descriptionEn: "The most prestigious tennis tournament in the world! Centre Court ticket, charming Wimbledon Village accommodation and the classic strawberries and cream experience.",
    highlights: ["Centre Court — Debenture Seat premium", "Wimbledon Village — charme inglês", "Afternoon tea no All England Club", "Tour por Londres incluído"],
    highlightsEn: ["Centre Court — Premium Debenture Seat", "Wimbledon Village — English charm", "Afternoon tea at All England Club", "London tour included"],
    touristSpots: ["Big Ben", "Tower Bridge", "Buckingham Palace", "London Eye", "British Museum"],
    tags: ["wimbledon", "tenis", "inglaterra", "londres", "europa", "tennis"],
  },

  // === CARNAVAL ===
  {
    id: "carnival-rio-2027",
    event: "Carnaval do Rio 2027",
    eventEn: "Rio Carnival 2027",
    location: "Rio de Janeiro",
    country: "Brasil",
    countryEn: "Brazil",
    countryCode: "BR",
    date: "Fevereiro 2027",
    dateEn: "February 2027",
    image: carnivalRio2027Img,
    price: 4990,
    originalPrice: 7490,
    badge: "🎭 Carnaval",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "GIG", airline: "GOL" },
    accommodation: { name: "Copacabana Beira-Mar", type: "Hotel 4★", distance: "5 min do Sambódromo" },
    tickets: { type: "Sambódromo", section: "Setor 9 - Arquibancada" },
    includes: ["Voo ida e volta", "5 noites hotel", "Ingresso Sambódromo", "Guia de blocos", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights hotel", "Sambódromo ticket", "Street party guide", "Airport transfer"],
    description: "O maior carnaval do planeta! Assista aos desfiles no Sambódromo, fique em hotel beira-mar em Copacabana e viva a energia dos blocos de rua do Rio.",
    descriptionEn: "The biggest carnival on the planet! Watch the parades at the Sambódromo, stay at a beachfront Copacabana hotel and feel the energy of Rio's street parties.",
    highlights: ["Desfiles das escolas de samba campeãs", "Hotel frente ao mar em Copacabana", "Guia completo dos blocos de rua", "Passeio pelo Cristo Redentor"],
    highlightsEn: ["Champion samba school parades", "Beachfront hotel in Copacabana", "Complete street party guide", "Christ the Redeemer tour"],
    touristSpots: ["Cristo Redentor", "Pão de Açúcar", "Copacabana", "Ipanema", "Lapa"],
    tags: ["carnaval", "brasil", "rio de janeiro", "festa", "cultura", "carnival", "culture"],
  },

  // === NBA ===
  {
    id: "nba-finals-2027",
    event: "NBA Finals 2027",
    eventEn: "NBA Finals 2027",
    location: "A definir",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Junho 2027",
    dateEn: "June 2027",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=500&fit=crop",
    price: 24990,
    originalPrice: 37490,
    badge: "🏀 NBA",
    category: "basketball",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "JFK", airline: "American Airlines" },
    accommodation: { name: "Hotel próximo à arena", type: "Hotel 4★", distance: "10 min da arena" },
    tickets: { type: "NBA Finals", section: "Upper Bowl" },
    includes: ["Voo ida e volta", "5 noites hotel", "Ingresso Game 1", "Tour pela arena", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights hotel", "Game 1 ticket", "Arena tour", "Airport transfer"],
    description: "Viva a emoção das finais da NBA! Ingresso para assistir aos melhores jogadores de basquete do planeta em ação, com hospedagem 4 estrelas.",
    descriptionEn: "Experience the thrill of the NBA Finals! Watch the best basketball players on the planet in action, with 4-star accommodation.",
    highlights: ["Ingresso NBA Finals", "Tour pela arena oficial", "NBA Store exclusiva", "Experiência de jogo autêntica americana"],
    highlightsEn: ["NBA Finals ticket", "Official arena tour", "Exclusive NBA Store", "Authentic American game experience"],
    touristSpots: ["NBA Store", "Basketball Hall of Fame", "Arena oficial NBA", "Centro da cidade-sede"],
    tags: ["nba", "basquete", "eua", "estados unidos", "esporte", "basketball", "sport"],
  },

  // === ROCK IN RIO ===
  {
    id: "rock-in-rio-2026",
    event: "Rock in Rio 2026",
    eventEn: "Rock in Rio 2026",
    location: "Rio de Janeiro",
    country: "Brasil",
    countryEn: "Brazil",
    countryCode: "BR",
    date: "Setembro 2026",
    dateEn: "September 2026",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop",
    price: 3990,
    originalPrice: 5990,
    badge: "🎸 Festival",
    category: "music",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "GIG", airline: "LATAM Airlines" },
    accommodation: { name: "Hotel Barra da Tijuca", type: "Hotel 3★", distance: "10 min do Parque Olímpico" },
    tickets: { type: "Rock in Rio", section: "Pista Premium — 2 dias" },
    includes: ["Voo ida e volta", "4 noites hotel", "2 ingressos Rock in Rio", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "4 nights hotel", "2 Rock in Rio tickets", "Airport transfer"],
    description: "O maior festival de música da América Latina! 2 dias de Rock in Rio com hospedagem na Barra da Tijuca e transporte incluso.",
    descriptionEn: "The biggest music festival in Latin America! 2 days of Rock in Rio with Barra da Tijuca accommodation and transport included.",
    highlights: ["2 dias de festival", "Palco Mundo", "Artistas internacionais", "Gastronomia no festival"],
    highlightsEn: ["2 festival days", "World Stage", "International artists", "Festival gastronomy"],
    touristSpots: ["Cristo Redentor", "Praia de Copacabana", "Pão de Açúcar", "Jardim Botânico", "Lagoa Rodrigo de Freitas"],
    tags: ["rock in rio", "festival", "musica", "brasil", "rio de janeiro", "music"],
  },

  // === ROLAND GARROS ===
  {
    id: "roland-garros-2026",
    event: "Roland Garros 2026",
    eventEn: "Roland Garros 2026",
    location: "Paris",
    country: "França",
    countryEn: "France",
    countryCode: "FR",
    date: "Junho 2026",
    dateEn: "June 2026",
    image: "https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=800&h=500&fit=crop",
    price: 15990,
    originalPrice: 23490,
    badge: "🎾 Tênis",
    category: "tennis",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "CDG", airline: "Air France" },
    accommodation: { name: "Hotel Saint-Germain", type: "Hotel 4★", distance: "15 min de Roland Garros" },
    tickets: { type: "Quartas de Final", section: "Philippe-Chatrier" },
    includes: ["Voo ida e volta", "5 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "5 nights hotel", "2 tickets", "Airport transfer", "Travel insurance"],
    description: "O saibro mais famoso do mundo! Assista às quartas de final em Roland Garros e desfrute de Paris no verão europeu.",
    descriptionEn: "The most famous clay court in the world! Watch the quarter-finals at Roland Garros and enjoy Paris in the European summer.",
    highlights: ["Court Philippe-Chatrier", "Gastronomia francesa no torneio", "Paris no verão", "Tour guiado por Paris"],
    highlightsEn: ["Court Philippe-Chatrier", "French gastronomy at the tournament", "Paris in summer", "Guided Paris tour"],
    touristSpots: ["Torre Eiffel", "Louvre", "Montmartre", "Champs-Élysées", "Notre-Dame"],
    tags: ["roland garros", "tenis", "paris", "franca", "europa", "tennis"],
  },

  // === COACHELLA ===
  {
    id: "coachella-2027",
    event: "Coachella 2027",
    eventEn: "Coachella 2027",
    location: "Indio, Califórnia",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Abril 2027",
    dateEn: "April 2027",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=500&fit=crop",
    price: 14990,
    originalPrice: 22490,
    badge: "🎵 Festival",
    category: "music",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "LAX", airline: "LATAM Airlines" },
    accommodation: { name: "Resort Palm Springs", type: "Resort", distance: "30 min do festival" },
    tickets: { type: "Weekend Pass", section: "General Admission — 3 dias" },
    includes: ["Voo ida e volta", "5 noites resort", "Passe 3 dias Coachella", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "5 nights resort", "3-day Coachella pass", "Airport transfer", "Travel insurance"],
    description: "O festival mais icônico do mundo! Três dias de música no deserto da Califórnia com hospedagem em resort em Palm Springs.",
    descriptionEn: "The world's most iconic festival! Three days of music in the California desert with resort accommodation in Palm Springs.",
    highlights: ["3 dias de festival", "Line-up internacional", "Arte e instalações no deserto", "Pool parties em Palm Springs"],
    highlightsEn: ["3 festival days", "International lineup", "Desert art installations", "Palm Springs pool parties"],
    touristSpots: ["Joshua Tree National Park", "Palm Springs", "Los Angeles", "Hollywood", "Santa Monica"],
    tags: ["coachella", "festival", "musica", "eua", "california", "estados unidos", "music"],
  },

  // === COPA AMÉRICA 2028 ===
  {
    id: "copa-america-2028",
    event: "Copa América 2028",
    eventEn: "Copa América 2028",
    location: "Buenos Aires",
    country: "Argentina",
    countryEn: "Argentina",
    countryCode: "AR",
    date: "Junho 2028",
    dateEn: "June 2028",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=500&fit=crop",
    price: 7990,
    originalPrice: 11990,
    badge: "⚽ Copa América",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "EZE", airline: "Aerolíneas Argentinas" },
    accommodation: { name: "Hotel Palermo Soho", type: "Hotel 4★", distance: "20 min do Monumental" },
    tickets: { type: "Fase de Grupos", section: "Platea" },
    includes: ["Voo ida e volta", "5 noites hotel", "2 ingressos", "Transfer aeroporto", "City tour"],
    includesEn: ["Round-trip flight", "5 nights hotel", "2 tickets", "Airport transfer", "City tour"],
    description: "Copa América na Argentina! Jogos no lendário Monumental de Núñez com hospedagem no charmoso Palermo Soho.",
    descriptionEn: "Copa América in Argentina! Games at the legendary Monumental de Núñez with accommodation in charming Palermo Soho.",
    highlights: ["Estádio Monumental", "Palermo Soho & Palermo Hollywood", "Churrasco argentino", "Shows de tango"],
    highlightsEn: ["Monumental Stadium", "Palermo Soho & Palermo Hollywood", "Argentine BBQ", "Tango shows"],
    touristSpots: ["La Boca", "Recoleta", "Puerto Madero", "San Telmo", "Teatro Colón"],
    tags: ["copa america", "futebol", "argentina", "buenos aires", "america do sul", "football"],
  },

  // === MUNDIAL DE CLUBES 2025 ===
  {
    id: "club-wc-2025",
    event: "Mundial de Clubes FIFA 2025",
    eventEn: "FIFA Club World Cup 2025",
    location: "Miami / New York",
    country: "Estados Unidos",
    countryEn: "United States",
    countryCode: "US",
    date: "Junho 2025",
    dateEn: "June 2025",
    image: "https://images.unsplash.com/photo-1522778526097-ce0a22ceb253?w=800&h=500&fit=crop",
    price: 15490,
    originalPrice: 23290,
    badge: "🏆 Clubes",
    category: "football",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MIA", airline: "LATAM Airlines" },
    accommodation: { name: "Hotel Brickell Miami", type: "Hotel 4★", distance: "15 min do estádio" },
    tickets: { type: "Fase de Grupos", section: "Categoria 2" },
    includes: ["Voo ida e volta", "7 noites hotel", "2 ingressos", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "7 nights hotel", "2 tickets", "Airport transfer", "Travel insurance"],
    description: "O novo Mundial de Clubes da FIFA com 32 times! Assista aos maiores clubes do mundo se enfrentarem nos EUA.",
    descriptionEn: "The new FIFA Club World Cup with 32 teams! Watch the world's biggest clubs compete in the US.",
    highlights: ["32 clubes do mundo todo", "Estádios modernos nos EUA", "Atmosphera única de clubes", "Miami Beach pós-jogo"],
    highlightsEn: ["32 clubs worldwide", "Modern US stadiums", "Unique club atmosphere", "Post-game Miami Beach"],
    touristSpots: ["South Beach", "Wynwood Walls", "Little Havana", "Key West", "Everglades"],
    tags: ["mundial clubes", "fifa", "futebol", "eua", "miami", "estados unidos", "world cup", "football"],
  },

  // === OKTOBERFEST ===
  {
    id: "oktoberfest-2026",
    event: "Oktoberfest 2026",
    eventEn: "Oktoberfest 2026",
    location: "Munique",
    country: "Alemanha",
    countryEn: "Germany",
    countryCode: "DE",
    date: "Setembro-Outubro 2026",
    dateEn: "September-October 2026",
    image: oktoberfest2026Img,
    price: 12990,
    originalPrice: 18990,
    badge: "🍺 Festival",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MUC", airline: "Lufthansa" },
    accommodation: { name: "Hotel Centro de Munique", type: "Hotel 3★", distance: "10 min do Theresienwiese" },
    tickets: { type: "Reserva em Tenda", section: "Hofbräu-Festzelt" },
    includes: ["Voo ida e volta", "5 noites hotel", "Reserva em tenda oficial", "Tour cervejarias", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights hotel", "Official tent reservation", "Brewery tour", "Airport transfer"],
    description: "A maior festa da cerveja do mundo! Reserva garantida em tenda oficial, tour por cervejarias tradicionais e imersão na cultura bávara.",
    descriptionEn: "The world's biggest beer festival! Guaranteed official tent reservation, traditional brewery tour, and Bavarian culture immersion.",
    highlights: ["Reserva em tenda oficial Hofbräu", "Tour por cervejarias centenárias", "Desfile tradicional de abertura", "Gastronomia bávara autêntica"],
    highlightsEn: ["Official Hofbräu tent reservation", "Century-old brewery tour", "Traditional opening parade", "Authentic Bavarian cuisine"],
    touristSpots: ["Marienplatz", "Englischer Garten", "Nymphenburg Palace", "BMW Museum", "Dachau Memorial"],
    tags: ["oktoberfest", "cerveja", "alemanha", "munique", "europa", "festival", "cultura", "beer", "culture"],
  },

  // === FESTIVAL DE CANNES ===
  {
    id: "cannes-2027",
    event: "Festival de Cinema de Cannes 2027",
    eventEn: "Cannes Film Festival 2027",
    location: "Cannes",
    country: "França",
    countryEn: "France",
    countryCode: "FR",
    date: "Maio 2027",
    dateEn: "May 2027",
    image: cannes2027Img,
    price: 19990,
    originalPrice: 29990,
    badge: "🎬 Cinema",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "NCE", airline: "Air France" },
    accommodation: { name: "Hotel La Croisette", type: "Hotel 4★", distance: "5 min do Palais des Festivals" },
    tickets: { type: "Cinéfondation Pass", section: "Sessões abertas ao público" },
    includes: ["Voo ida e volta", "5 noites hotel", "Pass cinéfilo", "Tour Riviera Francesa", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights hotel", "Cinephile pass", "French Riviera tour", "Airport transfer"],
    description: "O festival de cinema mais glamouroso do mundo! Assista a premières, passeie pela Croisette e viva o charme da Côte d'Azur.",
    descriptionEn: "The world's most glamorous film festival! Watch premieres, stroll the Croisette and live the Côte d'Azur charm.",
    highlights: ["Sessões de cinema exclusivas", "Red carpet na Croisette", "Tour por Nice e Monaco", "Gastronomia provençal"],
    highlightsEn: ["Exclusive film screenings", "Red carpet on the Croisette", "Nice and Monaco tour", "Provençal cuisine"],
    touristSpots: ["La Croisette", "Île Sainte-Marguerite", "Nice", "Monaco", "Saint-Tropez"],
    tags: ["cannes", "cinema", "franca", "europa", "festival", "cultura", "film", "culture"],
  },

  // === DIA DE LOS MUERTOS ===
  {
    id: "dia-muertos-2026",
    event: "Día de los Muertos 2026",
    eventEn: "Day of the Dead 2026",
    location: "Cidade do México",
    country: "México",
    countryEn: "Mexico",
    countryCode: "MX",
    date: "Outubro-Novembro 2026",
    dateEn: "October-November 2026",
    image: diaMuertos2026Img,
    price: 8990,
    originalPrice: 13490,
    badge: "💀 Cultural",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MEX", airline: "Aeroméxico" },
    accommodation: { name: "Hotel Centro Histórico", type: "Hotel 4★", distance: "No coração da cidade" },
    tickets: { type: "Tour guiado", section: "Desfile + Cemitérios" },
    includes: ["Voo ida e volta", "4 noites hotel", "Tour guiado completo", "Oficina de altar", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "4 nights hotel", "Full guided tour", "Altar workshop", "Airport transfer"],
    description: "Viva a tradição mais emblemática do México! Assista ao Grande Desfile, visite cemitérios decorados e participe de oficinas de altares tradicionais.",
    descriptionEn: "Experience Mexico's most emblematic tradition! Watch the Grand Parade, visit decorated cemeteries and participate in traditional altar workshops.",
    highlights: ["Grande Desfile do Día de los Muertos", "Cemitério de Mixquic decorado", "Oficina de calaveritas de açúcar", "Gastronomia mexicana de temporada"],
    highlightsEn: ["Grand Day of the Dead Parade", "Decorated Mixquic cemetery", "Sugar skull workshop", "Seasonal Mexican cuisine"],
    touristSpots: ["Zócalo", "Teotihuacán", "Xochimilco", "Museu Frida Kahlo", "Chapultepec"],
    tags: ["dia de los muertos", "mexico", "cultura", "tradição", "day of the dead", "culture"],
  },

  // === FESTIVAL HOLI ===
  {
    id: "holi-india-2027",
    event: "Festival Holi 2027",
    eventEn: "Holi Festival 2027",
    location: "Jaipur",
    country: "Índia",
    countryEn: "India",
    countryCode: "IN",
    date: "Março 2027",
    dateEn: "March 2027",
    image: holiIndia2027Img,
    price: 15990,
    originalPrice: 23990,
    badge: "🎨 Festival",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "DEL", airline: "Emirates" },
    accommodation: { name: "Haveli Heritage Hotel", type: "Hotel Heritage", distance: "Centro de Jaipur" },
    tickets: { type: "Festival completo", section: "Celebração pública" },
    includes: ["Voo ida e volta", "7 noites hotel", "Tour Triângulo Dourado", "Festival Holi guiado", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "7 nights hotel", "Golden Triangle tour", "Guided Holi festival", "Airport transfer", "Travel insurance"],
    description: "O festival das cores mais vibrante do mundo! Celebre o Holi em Jaipur com tour pelo Triângulo Dourado (Delhi, Agra e Jaipur).",
    descriptionEn: "The world's most vibrant festival of colors! Celebrate Holi in Jaipur with a Golden Triangle tour (Delhi, Agra, and Jaipur).",
    highlights: ["Celebração Holi em Jaipur", "Visita ao Taj Mahal", "Tour pelo Forte Amber", "Experiência gastronômica indiana"],
    highlightsEn: ["Holi celebration in Jaipur", "Taj Mahal visit", "Amber Fort tour", "Indian culinary experience"],
    touristSpots: ["Hawa Mahal", "Forte Amber", "Taj Mahal", "Red Fort Delhi", "Jantar Mantar"],
    tags: ["holi", "india", "festival", "cultura", "cores", "jaipur", "culture", "colors"],
  },

  // === AURORA BOREAL ===
  {
    id: "aurora-boreal-2027",
    event: "Aurora Boreal na Noruega",
    eventEn: "Northern Lights in Norway",
    location: "Tromsø",
    country: "Noruega",
    countryEn: "Norway",
    countryCode: "NO",
    date: "Janeiro 2027",
    dateEn: "January 2027",
    image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800&h=500&fit=crop",
    price: 21990,
    originalPrice: 31990,
    badge: "🌌 Natureza",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "OSL", airline: "KLM" },
    accommodation: { name: "Glass Igloo Lodge", type: "Lodge Premium", distance: "Arredores de Tromsø" },
    tickets: { type: "Safari Aurora", section: "Grupo VIP" },
    includes: ["Voo ida e volta", "5 noites hospedagem", "Safari aurora boreal", "Passeio de trenó com huskies", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "5 nights accommodation", "Northern lights safari", "Husky sledding", "Airport transfer", "Travel insurance"],
    description: "Uma experiência mágica na Noruega! Durma em iglu de vidro sob a aurora boreal, passeie de trenó com huskies e explore os fiordes árticos.",
    descriptionEn: "A magical Norwegian experience! Sleep in a glass igloo under the northern lights, go husky sledding, and explore the Arctic fjords.",
    highlights: ["Iglu de vidro com vista para aurora", "Safari de aurora boreal VIP", "Trenó puxado por huskies", "Cruzeiro pelos fiordes"],
    highlightsEn: ["Glass igloo with aurora view", "VIP northern lights safari", "Husky-pulled sled ride", "Fjord cruise"],
    touristSpots: ["Catedral do Ártico", "Polaria", "Fiordes de Tromsø", "Cabo Norte", "Ilhas Lofoten"],
    tags: ["aurora boreal", "noruega", "natureza", "tromso", "europa", "northern lights", "norway", "nature"],
  },

  // === CHERRY BLOSSOM JAPAN ===
  {
    id: "sakura-japan-2027",
    event: "Temporada de Sakura no Japão",
    eventEn: "Cherry Blossom Season in Japan",
    location: "Tóquio / Kyoto",
    country: "Japão",
    countryEn: "Japan",
    countryCode: "JP",
    date: "Março-Abril 2027",
    dateEn: "March-April 2027",
    image: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&h=500&fit=crop",
    price: 19490,
    originalPrice: 28990,
    badge: "🌸 Cultural",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "NRT", airline: "Japan Airlines" },
    accommodation: { name: "Ryokan Tradicional + Hotel Moderno", type: "Misto", distance: "Centros de Tóquio e Kyoto" },
    tickets: { type: "Japan Rail Pass", section: "7 dias ilimitado" },
    includes: ["Voo ida e volta", "8 noites hospedagem", "Japan Rail Pass 7 dias", "Tour guiado em português", "Transfer aeroporto", "Seguro viagem"],
    includesEn: ["Round-trip flight", "8 nights accommodation", "7-day Japan Rail Pass", "Guided tour", "Airport transfer", "Travel insurance"],
    description: "Viva a magia dos sakuras no Japão! Roteiro por Tóquio e Kyoto durante a floração das cerejeiras, com hospedagem em ryokan tradicional e trem-bala.",
    descriptionEn: "Experience the magic of cherry blossoms in Japan! Tokyo and Kyoto itinerary during cherry blossom season, with traditional ryokan stay and bullet train.",
    highlights: ["Hanami (contemplação das cerejeiras)", "Noite em ryokan com onsen", "Trem-bala Shinkansen", "Cerimônia do chá em Kyoto"],
    highlightsEn: ["Hanami (cherry blossom viewing)", "Ryokan night with onsen", "Shinkansen bullet train", "Tea ceremony in Kyoto"],
    touristSpots: ["Templo Fushimi Inari", "Shibuya Crossing", "Arashiyama Bamboo Grove", "Kinkaku-ji", "Monte Fuji"],
    tags: ["sakura", "japao", "cerejeiras", "cultura", "toquio", "kyoto", "japan", "cherry blossom", "culture"],
  },

  // === TOMORROWLAND ===
  {
    id: "tomorrowland-2026",
    event: "Tomorrowland 2026",
    eventEn: "Tomorrowland 2026",
    location: "Boom",
    country: "Bélgica",
    countryEn: "Belgium",
    countryCode: "BE",
    date: "Julho 2026",
    dateEn: "July 2026",
    image: tomorrowland2026Img,
    price: 16990,
    originalPrice: 24990,
    badge: "🎶 Festival",
    category: "music",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "BRU", airline: "Brussels Airlines" },
    accommodation: { name: "DreamVille Camping Magnificent Greens", type: "Camping Festival", distance: "Dentro do festival" },
    tickets: { type: "Full Madness Pass", section: "3 dias + DreamVille" },
    includes: ["Voo ida e volta", "6 noites hospedagem", "Full Madness Pass 3 dias", "DreamVille camping", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "6 nights accommodation", "3-day Full Madness Pass", "DreamVille camping", "Airport transfer"],
    description: "O maior festival de música eletrônica do planeta! Full Madness Pass de 3 dias com camping no DreamVille e os melhores DJs do mundo.",
    descriptionEn: "The world's biggest electronic music festival! 3-day Full Madness Pass with DreamVille camping and the world's best DJs.",
    highlights: ["Palco principal espetacular", "DJs headliners mundiais", "DreamVille — vila do festival", "Cenários de conto de fadas"],
    highlightsEn: ["Spectacular main stage", "World-class headliner DJs", "DreamVille — festival village", "Fairy tale scenery"],
    touristSpots: ["Grand Place Bruxelas", "Bruges", "Atomium", "Manneken Pis", "Antuérpia"],
    tags: ["tomorrowland", "festival", "musica", "belgica", "europa", "eletronica", "music", "electronic"],
  },

  // === VENDIMIA MENDOZA ===
  {
    id: "vendimia-2027",
    event: "Festa da Vendimia 2027",
    eventEn: "Vendimia Harvest Festival 2027",
    location: "Mendoza",
    country: "Argentina",
    countryEn: "Argentina",
    countryCode: "AR",
    date: "Março 2027",
    dateEn: "March 2027",
    image: vendimia2027Img,
    price: 6990,
    originalPrice: 10490,
    badge: "🍷 Cultural",
    category: "culture",
    flight: { from: "São Paulo (GRU)", fromCode: "GRU", toCode: "MDZ", airline: "Aerolíneas Argentinas" },
    accommodation: { name: "Lodge em Vinícola", type: "Lodge", distance: "Valle de Uco" },
    tickets: { type: "Vendimia Central", section: "Tribuna Preferencial" },
    includes: ["Voo ida e volta", "5 noites hospedagem", "Ingresso Vendimia", "Tour vinícolas premium", "Transfer aeroporto"],
    includesEn: ["Round-trip flight", "5 nights accommodation", "Vendimia ticket", "Premium winery tour", "Airport transfer"],
    description: "A maior festa do vinho da América do Sul! Desfile da colheita, degustação em vinícolas premium e hospedagem em lodge com vista para os Andes.",
    descriptionEn: "South America's biggest wine festival! Harvest parade, premium winery tastings, and lodge with Andes views.",
    highlights: ["Desfile da colheita da uva", "Degustação em 5 vinícolas premium", "Vista para a Cordilheira dos Andes", "Show de encerramento no anfiteatro"],
    highlightsEn: ["Grape harvest parade", "Tasting at 5 premium wineries", "Andes mountain views", "Closing show at amphitheater"],
    touristSpots: ["Vinícolas de Luján de Cuyo", "Aconcágua", "Valle de Uco", "Parque General San Martín", "Puente del Inca"],
    tags: ["vendimia", "vinho", "argentina", "mendoza", "cultura", "wine", "culture"],
  },
];

// ============================================================
// Upcoming-event helpers
// ============================================================

const PT_MONTHS: Record<string, number> = {
  janeiro: 0, fevereiro: 1, março: 2, marco: 2, abril: 3, maio: 4, junho: 5,
  julho: 6, agosto: 7, setembro: 8, outubro: 9, novembro: 10, dezembro: 11,
};

/**
 * Parses a Portuguese date string (e.g. "Junho 2026", "Setembro-Outubro 2026",
 * "Março-Abril 2027") into the LAST day of the LAST month mentioned. The event
 * is considered upcoming until the end of that month.
 */
function parseEventEndDate(dateStr: string): Date | null {
  const lower = dateStr.toLowerCase();
  const yearMatch = lower.match(/\b(20\d{2})\b/);
  if (!yearMatch) return null;
  const year = parseInt(yearMatch[1], 10);

  // Collect all month names found, in order
  const months: number[] = [];
  for (const [name, idx] of Object.entries(PT_MONTHS)) {
    let from = 0;
    while (true) {
      const i = lower.indexOf(name, from);
      if (i === -1) break;
      months.push(idx);
      from = i + name.length;
    }
  }

  // Use the last month if any, otherwise December
  const monthIdx = months.length > 0 ? months[months.length - 1] : 11;
  // Last day of that month
  return new Date(year, monthIdx + 1, 0, 23, 59, 59);
}

/** True if the event has not yet ended. */
export function isEventUpcoming(pkg: EventPackage, now: Date = new Date()): boolean {
  const end = parseEventEndDate(pkg.date);
  if (!end) return true; // be permissive if parsing fails
  return end.getTime() >= now.getTime();
}

/** Filter helper: returns only upcoming packages. */
export function getUpcomingPackages(): EventPackage[] {
  return eventPackages.filter((p) => isEventUpcoming(p));
}

