// FlyCultura — Lista enxuta de cidades do mundo para autocomplete genérico.
// Usada como fallback quando o termo não corresponde a destinos curados ou eventos.
// Formato: "Cidade, País" (PT-BR). Não exaustiva — cobre os destinos mais buscados globalmente.

export interface WorldCity {
  name: string;     // Nome da cidade (PT)
  country: string;  // País (PT)
  aliases?: string[]; // Variantes (EN, acentos, código IATA)
}

export const worldCities: WorldCity[] = [
  // América do Sul
  { name: "São Paulo", country: "Brasil", aliases: ["sao paulo", "gru", "sp"] },
  { name: "Rio de Janeiro", country: "Brasil", aliases: ["rio", "gig"] },
  { name: "Brasília", country: "Brasil", aliases: ["brasilia", "bsb"] },
  { name: "Salvador", country: "Brasil", aliases: ["ssa"] },
  { name: "Recife", country: "Brasil", aliases: ["rec"] },
  { name: "Fortaleza", country: "Brasil", aliases: ["for"] },
  { name: "Florianópolis", country: "Brasil", aliases: ["floripa", "fln"] },
  { name: "Manaus", country: "Brasil", aliases: ["mao"] },
  { name: "Buenos Aires", country: "Argentina", aliases: ["eze"] },
  { name: "Bariloche", country: "Argentina" },
  { name: "Mendoza", country: "Argentina" },
  { name: "Santiago", country: "Chile", aliases: ["scl"] },
  { name: "Lima", country: "Peru", aliases: ["lim"] },
  { name: "Cusco", country: "Peru", aliases: ["cuz"] },
  { name: "Bogotá", country: "Colômbia", aliases: ["bogota", "bog"] },
  { name: "Cartagena", country: "Colômbia", aliases: ["ctg"] },
  { name: "Medellín", country: "Colômbia", aliases: ["medellin"] },
  { name: "Quito", country: "Equador", aliases: ["uio"] },
  { name: "Montevidéu", country: "Uruguai", aliases: ["montevideo", "mvd"] },
  { name: "Caracas", country: "Venezuela" },

  // América do Norte e Central
  { name: "New York", country: "Estados Unidos", aliases: ["nova york", "nyc", "jfk"] },
  { name: "Los Angeles", country: "Estados Unidos", aliases: ["la", "lax"] },
  { name: "Miami", country: "Estados Unidos", aliases: ["mia"] },
  { name: "Orlando", country: "Estados Unidos", aliases: ["mco"] },
  { name: "Las Vegas", country: "Estados Unidos", aliases: ["las"] },
  { name: "San Francisco", country: "Estados Unidos", aliases: ["sfo"] },
  { name: "Chicago", country: "Estados Unidos", aliases: ["ord"] },
  { name: "Boston", country: "Estados Unidos", aliases: ["bos"] },
  { name: "Washington", country: "Estados Unidos", aliases: ["dca", "iad"] },
  { name: "Seattle", country: "Estados Unidos", aliases: ["sea"] },
  { name: "Honolulu", country: "Estados Unidos", aliases: ["hawaii", "havai", "hnl"] },
  { name: "Toronto", country: "Canadá", aliases: ["yyz"] },
  { name: "Vancouver", country: "Canadá", aliases: ["yvr"] },
  { name: "Montreal", country: "Canadá", aliases: ["yul"] },
  { name: "Cidade do México", country: "México", aliases: ["mexico city", "mex"] },
  { name: "Cancún", country: "México", aliases: ["cancun", "cun"] },
  { name: "Cidade do Panamá", country: "Panamá", aliases: ["panama city", "pty"] },
  { name: "Havana", country: "Cuba" },
  { name: "São Domingos", country: "República Dominicana", aliases: ["santo domingo"] },

  // Europa
  { name: "Paris", country: "França", aliases: ["cdg"] },
  { name: "Nice", country: "França" },
  { name: "Marselha", country: "França", aliases: ["marseille"] },
  { name: "Londres", country: "Reino Unido", aliases: ["london", "lhr"] },
  { name: "Edimburgo", country: "Reino Unido", aliases: ["edinburgh"] },
  { name: "Manchester", country: "Reino Unido" },
  { name: "Madri", country: "Espanha", aliases: ["madrid", "mad"] },
  { name: "Barcelona", country: "Espanha", aliases: ["bcn"] },
  { name: "Sevilha", country: "Espanha", aliases: ["sevilla", "seville"] },
  { name: "Valência", country: "Espanha", aliases: ["valencia"] },
  { name: "Ibiza", country: "Espanha" },
  { name: "Lisboa", country: "Portugal", aliases: ["lisbon", "lis"] },
  { name: "Porto", country: "Portugal", aliases: ["opo"] },
  { name: "Madeira", country: "Portugal" },
  { name: "Roma", country: "Itália", aliases: ["rome", "fco"] },
  { name: "Milão", country: "Itália", aliases: ["milan", "milano", "mxp"] },
  { name: "Veneza", country: "Itália", aliases: ["venice", "venezia"] },
  { name: "Florença", country: "Itália", aliases: ["florence", "firenze"] },
  { name: "Nápoles", country: "Itália", aliases: ["napoli", "naples"] },
  { name: "Berlim", country: "Alemanha", aliases: ["berlin", "ber"] },
  { name: "Munique", country: "Alemanha", aliases: ["munich", "muc"] },
  { name: "Frankfurt", country: "Alemanha", aliases: ["fra"] },
  { name: "Hamburgo", country: "Alemanha", aliases: ["hamburg"] },
  { name: "Amsterdam", country: "Holanda", aliases: ["amsterda", "ams"] },
  { name: "Bruxelas", country: "Bélgica", aliases: ["brussels"] },
  { name: "Viena", country: "Áustria", aliases: ["vienna", "vie"] },
  { name: "Zurique", country: "Suíça", aliases: ["zurich", "zrh"] },
  { name: "Genebra", country: "Suíça", aliases: ["geneva"] },
  { name: "Praga", country: "República Tcheca", aliases: ["prague"] },
  { name: "Budapeste", country: "Hungria", aliases: ["budapest"] },
  { name: "Varsóvia", country: "Polônia", aliases: ["warsaw"] },
  { name: "Cracóvia", country: "Polônia", aliases: ["krakow"] },
  { name: "Atenas", country: "Grécia", aliases: ["athens", "ath"] },
  { name: "Santorini", country: "Grécia" },
  { name: "Mykonos", country: "Grécia" },
  { name: "Istambul", country: "Turquia", aliases: ["istanbul", "ist"] },
  { name: "Capadócia", country: "Turquia", aliases: ["cappadocia"] },
  { name: "Moscou", country: "Rússia", aliases: ["moscow"] },
  { name: "São Petersburgo", country: "Rússia", aliases: ["saint petersburg"] },
  { name: "Estocolmo", country: "Suécia", aliases: ["stockholm"] },
  { name: "Oslo", country: "Noruega" },
  { name: "Copenhague", country: "Dinamarca", aliases: ["copenhagen"] },
  { name: "Helsinque", country: "Finlândia", aliases: ["helsinki"] },
  { name: "Reykjavík", country: "Islândia", aliases: ["reykjavik", "iceland"] },
  { name: "Dublin", country: "Irlanda" },

  // Ásia
  { name: "Tóquio", country: "Japão", aliases: ["tokyo", "hnd", "nrt"] },
  { name: "Kyoto", country: "Japão", aliases: ["kyoto"] },
  { name: "Osaka", country: "Japão" },
  { name: "Seul", country: "Coreia do Sul", aliases: ["seoul", "icn"] },
  { name: "Pequim", country: "China", aliases: ["beijing", "pek"] },
  { name: "Xangai", country: "China", aliases: ["shanghai", "pvg"] },
  { name: "Hong Kong", country: "China", aliases: ["hkg"] },
  { name: "Taipé", country: "Taiwan", aliases: ["taipei"] },
  { name: "Bangkok", country: "Tailândia", aliases: ["bkk"] },
  { name: "Phuket", country: "Tailândia", aliases: ["hkt"] },
  { name: "Chiang Mai", country: "Tailândia" },
  { name: "Singapura", country: "Singapura", aliases: ["singapore", "sin"] },
  { name: "Kuala Lumpur", country: "Malásia", aliases: ["kul"] },
  { name: "Bali", country: "Indonésia", aliases: ["dps", "denpasar"] },
  { name: "Jakarta", country: "Indonésia", aliases: ["jacarta"] },
  { name: "Manila", country: "Filipinas" },
  { name: "Ho Chi Minh", country: "Vietnã", aliases: ["saigon", "saigão"] },
  { name: "Hanói", country: "Vietnã", aliases: ["hanoi"] },
  { name: "Mumbai", country: "Índia", aliases: ["bombay", "bom"] },
  { name: "Nova Deli", country: "Índia", aliases: ["new delhi", "delhi", "del"] },
  { name: "Goa", country: "Índia" },
  { name: "Dubai", country: "Emirados Árabes", aliases: ["dxb"] },
  { name: "Abu Dhabi", country: "Emirados Árabes" },
  { name: "Doha", country: "Catar", aliases: ["qatar"] },
  { name: "Tel Aviv", country: "Israel" },
  { name: "Jerusalém", country: "Israel", aliases: ["jerusalem"] },
  { name: "Amã", country: "Jordânia", aliases: ["amman"] },
  { name: "Beirute", country: "Líbano", aliases: ["beirut"] },

  // África
  { name: "Cairo", country: "Egito" },
  { name: "Marraquexe", country: "Marrocos", aliases: ["marrakech", "marrakesh"] },
  { name: "Casablanca", country: "Marrocos" },
  { name: "Cidade do Cabo", country: "África do Sul", aliases: ["cape town"] },
  { name: "Joanesburgo", country: "África do Sul", aliases: ["johannesburg"] },
  { name: "Nairóbi", country: "Quênia", aliases: ["nairobi"] },
  { name: "Zanzibar", country: "Tanzânia" },
  { name: "Adis Abeba", country: "Etiópia", aliases: ["addis ababa"] },
  { name: "Lagos", country: "Nigéria" },
  { name: "Acra", country: "Gana", aliases: ["accra"] },

  // Oceania
  { name: "Sydney", country: "Austrália", aliases: ["syd"] },
  { name: "Melbourne", country: "Austrália" },
  { name: "Brisbane", country: "Austrália" },
  { name: "Auckland", country: "Nova Zelândia" },
  { name: "Queenstown", country: "Nova Zelândia" },
  { name: "Fiji", country: "Fiji" },
  { name: "Bora Bora", country: "Polinésia Francesa" },

  // Caribe
  { name: "Punta Cana", country: "República Dominicana" },
  { name: "Nassau", country: "Bahamas" },
  { name: "Aruba", country: "Aruba" },
  { name: "Curaçao", country: "Curaçao", aliases: ["curacao"] },
  { name: "Barbados", country: "Barbados" },
  { name: "Jamaica", country: "Jamaica" },
  { name: "Maldivas", country: "Maldivas", aliases: ["maldives"] },
];
